module.exports = {
  teamNames: ['Frontendfrogs', 'FrontendFellows', 'Backendteam'],
  testTypes: [
    'api',
    'ui',
    'unit',
    'integration',
    'endToEnd',
    'performance',
    'security',
    'database',
    'accessibility',
    'mobile',
  ],
  testCategories: [
    'smoke',
    'regression',
    'sanity',
    'exploratory',
    'functional',
    'load',
    'stress',
    'usability',
    'compatibility',
    'alpha',
    'beta',
  ],
  googleSpreadsheetUrl:
    'https://docs.google.com/spreadsheets/d/1Y8tFpbNEKPtQWmo3U9idGxxoSB3zIbLrQFsllr1mySs/edit?gid=1812580685#gid=1812580685',
  googleKeyFilePath: './googleCredentials.json',
  testData: './cypress/results/output.json',
  csvDownloadsPath: './cypress/downloads',
  weeklySummaryStartDay: 'Monday',
};
